### PR TITLE
Polkadot v0.9.37

### LINKED ISSUE #174: upgrade to polkadot-0.9.37

### PR DESCRIPTION
**Pull request by pifragile**
closes #174

### CODE REVIEW

**Review by clangenb — APPROVED** [review]
Beautiful! I have nothing to add, if you tell me that you were able to run a local setup with it, I think it is ready to merge!

**Comment by pifragile** [comment]
after many build hours i made it work😅
Bildschirmfoto 2023-05-01 um 13 02 13
Bildschirmfoto 2023-05-01 um 13 02 56

**Comment by pifragile** [comment]
in order to run the parachain i had to [update](https://github.com/encointer/encointer-parachain/pull/171/commits/029e43d85274b08f23a84d8ecc23433a69bd1539) the rust toolchain, according to this [post](https://stackoverflow.com/questions/75955457/substrate-node-template-cannot-create-a-runtime-error-othercannot-deserialize). now the CI crashes? any idea how to quickly fix this?

**Comment by clangenb** [comment]
I suggest bumping srtool to the latest version in GitHub actions and see what happens. Also, you can remove the `profile = minimal` from the toolchain-file. Lastly, I bump the toolchain to the latest available version when I do a toolchain upgrade, i.e., 04/05/2023.

**Comment by pifragile** [comment]
@clangenb I tried to bump the rust version, but i keep getting the error mentioned in [this post](https://stackoverflow.com/questions/75955457/substrate-node-template-cannot-create-a-runtime-error-othercannot-deserialize)

**Pull request merged**
