### PR TITLE
Upgrade polka and pallets

### PR DESCRIPTION
**Pull request by brenzi**
did 
```
diener update -s --branch polkadot-v0.9.17
diener update -c --branch polkadot-v0.9.17
diener update -p --branch release-v0.9.17
```
then pushed branches named `polkadot-v0.9.17` on all these repos:
* encointer/typenum
* encointer/substrate-fixed
* encointer/geohash
* encointer/pallets
aligning scale codec / typeinfo / substrate-fixed versions

and referred to each others respective branches

### CODE REVIEW

**Review by clangenb — APPROVED** [review]
Looks good to me.

**Comment by clangenb** [comment]
Why did you do branch names for:

* encointer/typenum
* encointer/substrate-fixed
* encointer/geohash

They don't depend on substrate

**Comment by brenzi** [comment]
not on substrate, but scale codec version must match and it didn't seem straightforward how to do versioning of a fork when nothing changes within the crate, just dependencies need adjusting. To me it seems like a quite consistent approach to maintain polkadot-release branches. But happy to hear other approaches

**Comment by clangenb** [comment]
Oh, I did not see that scale codec has not been bumped yet on the polkadot-branch. I am fine with the approach, though.

**Pull request merged**
